branding:
  appName: "TeddyNote Chat"
  logoPath: "/logo.png"
  logoWidth: 28
  logoHeight: 28
  description: "테디노트 챗봇에게 무엇이든 물어보세요."
  fullDescription: "/full-description.md"

buttons:
  enableFileUpload: true
  chatInputPlaceholder: "궁금한 내용을 물어보세요."

threads:
  showHistory: true
  enableDeletion: true
  enableTitleEdit: true
  autoGenerateTitles: true
  sidebarOpenByDefault: true

theme:
  fontFamily: "serif"
  fontSize: "large"
  colorScheme: "light"

ui:
  autoCollapseToolCalls: true
  chatWidth: "wide"
